# Generated by Django 5.0.4 on 2026-06-06 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('current_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_24h', models.DecimalField(decimal_places=15, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
