# Generated by Django 5.0.4 on 2026-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='asset',
            name='volume_24h',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
    ]
