# Generated by Django 5.0.4 on 2026-06-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_current_price_alter_asset_volume_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='icon_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
