# Generated by Django 5.0.4 on 2026-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
