# Generated by Django 5.0.4 on 2026-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', '-created_at'], name='ai_chatmess_chat_id_4dd565_idx'),
        ),
    ]
