# Generated by Django 5.0.4 on 2026-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_cryptotransaction_cryptowallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
