# Generated by Django 5.0.4 on 2026-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_cryptowallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptotransaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='cryptotransaction',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cryptotransaction',
            name='usdt_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('exchange', 'Exchange')], max_length=20),
        ),
    ]
