# Generated by Django 5.0.4 on 2026-08-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_portfoliosnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='from_asset',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
