# Generated by Django 5.0.4 on 2026-09-30 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_cryptotransaction_from_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='wallet_tran_stripe__9480c0_idx',
        ),
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['created_at'], name='wallet_cryp_created_e79f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='wallet_tran_user_id_46afdf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='wallet_tran_status_58a2dc_idx'),
        ),
    ]
