# Generated by Django 5.0.4 on 2026-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_transaction_wallet_tran_stripe__9480c0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
